#Configuation for robot odometry EKF
#
frequency: 50

two_d_mode: true
publish_tf: true

# Complete the frames section
map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: map

# Complete the odom0 configuration
odom0: /tigra/wheel_odom
odom0_config: 
  [true, true, false,
  false, false, true,
  false,  false,  false,
  false, false, false,
  false, false, false,]
odom0_queue_size: 10
odom0_nodelay: true
odom0_differential: false
odom0_relative: false

# Complete the imu0 configuration
imu0: /tigra/imu
imu0_config:
   [false, false, false,
   false,  false,  true,
   false, false, false,
   true,  true,  true,
   true,  true,  false,]
imu0_queue_size: 10
imu0_nodelay: true
imu0_differential: false
imu0_relative: false

odom1: /tigra/nav/gps
odom1_config: 
  [true,  true,  false,
   false, false, false,
   false, false, false,
   false, false, false,
   false, false, false]
odom1_queue_size: 10
odom1_nodelay: true
odom1_differential: false
odom1_relative: false



initial_estimate_covariance: [7.11*1e-8, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    7.11*1e-8, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    2.77*1e-8, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0.071, 0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0.071, 0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e5,  0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0.028, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]
